### ISSUE TITLE
No such file to load -- user_import.rb

### ISSUE THREAD

**Issue by BrankoH** [nanego/redmine_user_import#9]
Redmine 4.1.1.stable.20294

bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine)
rake aborted!
LoadError: No such file to load -- user_import.rb

**Comment by nanego** [comment]
Hello @BrankoH 
You certainly installed the latest version of the plugin, which is not compatible with Redmine 4.1.1
You probably should use this older version: https://github.com/nanego/redmine_user_import/tree/v4.1
